### ISSUE TITLE
contentStyle for Dialog.Container

### ISSUE THREAD

**Issue by yeong0809** [mmazzarolo/react-native-dialog#58] opened 2019-07-29 02:59 UTC
ContentStyle seem like not working fine for iOS side and it is working in Android. When I try to change the background color for the Container. The backgroundColor is not affecting on the background color.  

Screenshot
![Screenshot 2019-07-29 at 10 56 25 AM](https://user-images.githubusercontent.com/31876283/62019049-c14f2380-b1ef-11e9-9e6e-7d7401d0624d.png)

Code:
`<Dialog.Container contentStyle={{ backgroundColor: background }}>`

**Comment by Desteel** [comment] 2019-10-02 08:00
> ContentStyle seem like not working fine for iOS side and it is working in Android. When I try to change the background color for the Container. The backgroundColor is not affecting on the background color.
> 
> Screenshot
> ![Screenshot 2019-07-29 at 10 56 25 AM](https://user-images.githubusercontent.com/31876283/62019049-c14f2380-b1ef-11e9-9e6e-7d7401d0624d.png)
> 
> Code:
> `<Dialog.Container contentStyle={{ backgroundColor: background }}>`

In iOs you need use this
```javascript
<Dialog.Container
        visible={this.isOpen}
        blurStyle={{ backgroundColor: "red" }}
        {...positioningButtonsStyle}
>
```

but this prop is not in types for this library and if you use typescript you need to add them.

**Comment by mmazzarolo** [comment] 2020-10-11 09:29
👋 I'm closing this issue because I just did a complete refactoring of `react-native-dialog`. Feel free to open a new one if the issue is still there.

**Closed by mmazzarolo** 2020-10-11 09:29 UTC
