### ISSUE TITLE
Container visible Doesn't work when click

### ISSUE THREAD

**Issue by AndreySevcenko** [mmazzarolo/react-native-dialog#48] opened 2019-05-14 11:21 UTC
A complete example's codes doesn't work in the README.

Firstly `dialogVisible : false ` is to loading,  i clicked on the TouchableOpacity in order to get `dialogVisible : true`, but doesnt work and i cant see modal.

But Firstly `dialogVisible : true` is to loading, is succes , is worked ,also i clicked in order to get `dialogVisible : false` , is closed to modal  no problem but after i clicked when for open modal , doesnt work and i cant see modal

Is my problem ,i dont know, I'll be glad if you can help me

**Comment by oreshkoandrei** [comment] 2019-06-26 18:13
any update on this ?

**Comment by brien-crean** [comment] 2019-06-27 00:00
I have the same issue. Changing state doesn't show the dialog.
I just implemented a simple hack to get it to display.

`_renderRenameDialog() {
    return this.state.dialogVisible ? (
      <Dialog.Container visible={true}>
        <Dialog.Title>Rename Item</Dialog.Title>
        <Dialog.Input
          placeholder={this.state.name}
          onChangeText={this.handleTextChange}
        />
        <Dialog.Button label='Cancel' onPress={this.handleCancel} />
        <Dialog.Button label='OK' onPress={this.handleOK} />
      </Dialog.Container>
    ) : null
  }`

**Comment by mmazzarolo** [comment] 2019-06-27 09:37
🤔 what version of RN are you using? This sounds strange, this component hasn't been updated in a while...

**Comment by brien-crean** [comment] 2019-06-27 18:07
I'm running version 0.53 which is quite old. We are pinned to it for a little while unfortunately.

I just created two projects with react-native init. One at v0.53 and one at the latest (0.59.9). It has the same issue on 0.53 but works fine on 0.59.9!

**Comment by mmazzarolo** [comment] 2019-06-27 19:05
Ouch :( Thanks for testing it on the latest version. Not sure what could be causing the issue here... maybe that version of RN has an issue with the modal used underneath?

**Comment by brien-crean** [comment] 2019-07-12 20:22
Yeah probably. I'm also seeing other issues related to Modals causing weird crashes on that RN version so I'm upgrading!

**Comment by lylest** [comment] 2019-08-20 08:03
yeah am facing the same problem the modal doesn't show when you change the state I copied  all codes from official documentation

**Comment by mmazzarolo** [comment] 2019-08-20 09:16
@lylest on what version of RN are you?

**Comment by mmazzarolo** [comment] 2019-08-20 09:16
@lylest on what version of RN are you?

**Comment by lylest** [comment] 2019-08-20 09:28
I am using expo

  "dependencies": {
    "expo": "^34.0.1",
    "expo-file-system": "~6.0.0",
    "expo-image-picker": "~6.0.0",
    "expo-permissions": "~6.0.0",
    "expo-sharing": "~6.0.0",
    "firebase": "^6.3.5",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-dialog": "^5.6.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.1.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1"

**Comment by mmazzarolo** [comment] 2020-10-11 09:26
👋 I'm closing this issue because I just did a complete refactoring of `react-native-dialog`. Feel free to open a new one if the issue is still there.

**Closed by mmazzarolo** 2020-10-11 09:26 UTC
Labels: invalid
