### ISSUE TITLE
[BUG]: Autofocus for Dialog.Input component

### ISSUE THREAD

**Issue by r1ckyrockz** [mmazzarolo/react-native-dialog#63] opened 2019-11-27 07:57 UTC
I noticed a timing issue on android devices, if the component `<Dialog.Input />` got the property autofocus, the keyboard doesn't appear always. Sometimes it works, but after clicking twice, the keyboard is not shown.

Code Example:
```
<Dialog.Container visible onBackdropPress={...}>
  <Dialog.Title style={styles.title}>My Title</Dialog.Title>
  <Dialog.Input value={this.state.value} onChangeText={...} autofocus />
  <Dialog.Button label={'OK'} onPress={...} />
</Dialog.Container>
```

Extra Note:
I wrapped the `Dialog.Container` into a FC Component and exported it with memo. But to remove the memo, didn't take any effect to the problem.

```
const DialogContainer: React.FC<IProps> = props => (
  <Dialog.Container style...>
      {props.children}
    </Dialog.Container>
);

export default React.memo(DialogContainer);
```

Here is my setup:
```
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.26 GB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.11.1 - ~/.config/nvm/12.11.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.config/nvm/12.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.10.2 => 16.10.2
    react-native: 0.61.4 => 0.61.4
    react-native-dialog => 5.6.0
```

**Comment by mmazzarolo** [comment] 2020-10-11 09:30
👋 I'm closing this issue because I just did a complete refactoring of `react-native-dialog`. Feel free to open a new one if the issue is still there.

**Closed by mmazzarolo** 2020-10-11 09:30 UTC

**Comment by asowers1** [comment] 2021-05-12 20:09
Hi, I appear to be seeing this issue above (or something like it) in Android on version 8.0.1. If I leave `autofocus` as its default false, then I can tap the input and the keyboard presents itself appropriately. Any ideas?

**Comment by xiic** [comment] 2022-03-03 22:50
Having this issue on Android 7.1.2 as well. Only appears on some devices, and only sometimes. But once it occurs, there is no way to show the keyboard anymore (for Dialog.Input). The only thing that helps, is to terminate and restart the app.

Version: 9.2.1
