### ISSUE TITLE
Dialog buttons shorter caption on device only

### ISSUE THREAD

**Issue by LondonJammo** [mmazzarolo/react-native-dialog#35] opened 2019-02-08 10:22 UTC
The Dialog buttons (Cancel, Save) have their Label clipped on the device only. On the emulator they appear correct. I don't have any extra styling on these elements, just out the box.

Android device OP5t
Android 9
Oxygen 9.0.3

![screenshot_20190208-100727__01](https://user-images.githubusercontent.com/3718237/52472436-2c963200-2b8b-11e9-8aa4-acfc5de11bd3.jpg)

**Comment by ironhide0396** [comment] 2019-10-10 17:35
Facing the exact same issue , any help will be appreciated.

**Comment by Katariaa** [comment] 2019-10-21 10:35
Any updates of this? Did you fix it @LondonJammo ?

**Comment by mmazzarolo** [comment] 2020-10-11 09:30
👋 I'm closing this issue because I just did a complete refactoring of `react-native-dialog`. Feel free to open a new one if the issue is still there.

**Closed by mmazzarolo** 2020-10-11 09:30 UTC
