### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'child.type.name')

### ISSUE THREAD

**Issue by kushal98** [mmazzarolo/react-native-dialog#71] opened 2020-08-29 07:21 UTC
Hey,
Getting this issue any idea what it might be?

Thanks

**Comment by mmazzarolo** [comment] 2020-10-11 09:22
👋 I'm closing this issue because I just did a complete refactoring of `react-native-dialog`. Feel free to open a new one if the issue is still there.

**Closed by mmazzarolo** 2020-10-11 09:22 UTC
